version: "2.3"
services:

  greetgo-email-mongo:
    image: mongo:4.2.0
    mem_limit: 700M
    restart: always
    ports:
      - "31098:27017"
    volumes:
      - ./volumes/mongo:/data/db

  greetgo-email-mongo-express:
    image: mongo-express:0.54.0
    mem_limit: 200M
    restart: always
    depends_on:
      - greetgo-email-mongo
    ports:
      - "31099:8081"                                        # MONGO-EXPRESS   http://localhost:31099
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: cobalt
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 111
      ME_CONFIG_MONGODB_SERVER: greetgo-email-mongo
